GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQXNodXRvc2giLCJpYXQiOjE2MDIyOTQ4MjksImV4cCI6MTYwMjI5NTQyOX0.9l3hnFKq8ARwVTuzbOotuSnNnAKzDLJrqiWw6NSINgk
###
POST http://localhost:4000/register
Content-Type: application/json

{
	"username": "Ashutosh"
}